#infra docker compose file
services:
  db: 
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: witw #need to change down the line, insecure 
      MYSQL_USER: witw
      MYSQL_PASSWORD: witw
      MYSQL_ROOT_PASSWORD: witw
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uwitw", "-pwitw"] #this format avoids exec command parsing issues
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:7
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes #makes redis db persistant on crash or restart
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  dbdata:
  redisdata: